version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Europe/Amsterdam"
    labels:
      - dependencies
    reviewers:
      - "msrd0"
  - package-ecosystem: npm
    directory: "redoc/src"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Europe/Amsterdam"
    labels:
      - dependencies
