
stages:
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test-none:
  stage: test
  image: msrd0/rust:alpine
  before_script:
    - cargo -V
  script:
    - cargo test --all --no-default-features
  cache:
    paths:
      - cargo/
      - target/

test-all:
  stage: test
  image: msrd0/rust:alpine-tarpaulin
  before_script:
    - apk add --no-cache bash curl
    - cargo -V
  script:
    - cargo tarpaulin --all --all-features --exclude-files 'cargo/*' --exclude-files 'example/*' --out Xml
    - wget -qO- https://codecov.io/bash | bash -s -- -X gcov
  cache:
    paths:
      - cargo/
      - target/

readme:
  stage: test
  image: msrd0/rust:alpine-readme
  script:
    - cargo readme -r gotham_restful -t ../README.tpl >README.md.new
    - diff README.md README.md.new
