# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = [".", "./derive", "./example"]

[package]
name = "gotham_restful"
version = "0.2.0-dev"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "RESTful additions for the gotham web framework"
keywords = ["gotham", "rest", "restful", "web", "http"]
categories = ["web-programming", "web-programming::http-server"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/msrd0/gotham-restful"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[badges]
gitlab = { repository = "msrd0/gotham-restful", branch = "master" }

[dependencies]
base64 = { version = "0.13.0", optional = true }
chrono = { version = "0.4.19", features = ["serde"], optional = true }
cookie = { version = "0.14", optional = true }
futures-core = "0.3.7"
futures-util = "0.3.7"
gotham = { version = "0.5.0", default-features = false }
gotham_derive = "0.5.0"
gotham_middleware_diesel = { version = "0.2.0", optional = true }
gotham_restful_derive = "0.2.0-dev"
indexmap = { version = "1.3.2", optional = true }
jsonwebtoken = { version = "7.1.0", optional = true }
log = "0.4.8"
mime = "0.3.16"
once_cell = { version = "1.5", optional = true }
openapiv3 = { version = "0.3.2", optional = true }
regex = { version = "1.4", optional = true }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.58"
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
futures-executor = "0.3.5"
paste = "1.0"
pretty_env_logger = "0.4"
tokio = { version = "0.2", features = ["time"], default-features = false }
thiserror = "1.0.18"
trybuild = "1.0.27"

[features]
default = ["cors", "errorlog", "without-openapi"]
full = ["auth", "chrono", "cors", "database", "errorlog", "openapi", "uuid"]

auth = ["gotham_restful_derive/auth", "base64", "cookie", "jsonwebtoken"]
cors = []
database = ["gotham_restful_derive/database", "gotham_middleware_diesel"]
errorlog = []

# These features are exclusive - https://gitlab.com/msrd0/gotham-restful/-/issues/4
without-openapi = []
openapi = ["gotham_restful_derive/openapi", "indexmap", "once_cell", "openapiv3", "regex"]

[package.metadata.docs.rs]
no-default-features = true
features = ["full"]

[patch.crates-io]
gotham_restful = { path = "." }
gotham_restful_derive = { path = "./derive" }
