# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = [
	"gotham_restful",
	"gotham_restful_derive",
	"example"
]

[patch.crates-io]
gotham_restful = { path = "./gotham_restful" }
gotham_restful_derive = { path = "./gotham_restful_derive" }
