# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = ["derive", "example"]

[package]
name = "gotham_restful"
version = "0.1.0"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "RESTful additions for the gotham web framework"
keywords = ["gotham", "rest", "restful", "web", "http"]
license = "EPL-2.0 OR Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/msrd0/gotham-restful"

[badges]
gitlab = { repository = "msrd0/gotham-restful", branch = "master" }

[dependencies]
base64 = { version = "0.13.0", optional = true }
chrono = { version = "0.4.19", features = ["serde"], optional = true }
cookie = { version = "0.14", optional = true }
futures-core = "0.3.7"
futures-util = "0.3.7"
gotham = { version = "0.5.0", default-features = false }
gotham_derive = "0.5.0"
gotham_middleware_diesel = { version = "0.2.0", optional = true }
gotham_restful_derive = { version = "0.1.0" }
indexmap = { version = "1.3.2", optional = true }
itertools = { version = "0.10.0", optional = true }
jsonwebtoken = { version = "7.1.0", optional = true }
log = "0.4.8"
mime = "0.3.16"
openapiv3 = { version = "0.3.2", optional = true }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.58"
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
futures-executor = "0.3.5"
paste = "1.0"
thiserror = "1.0.18"
trybuild = "1.0.27"

[features]
default = ["cors", "errorlog"]
auth = ["gotham_restful_derive/auth", "base64", "cookie", "jsonwebtoken"]
cors = ["itertools"]
errorlog = []
database = ["gotham_restful_derive/database", "gotham_middleware_diesel"]
openapi = ["gotham_restful_derive/openapi", "indexmap", "openapiv3"]

[package.metadata.docs.rs]
all-features = true

[patch.crates-io]
gotham_restful = { path = "." }
gotham_restful_derive = { path = "./derive" }
