edition = "2018"
max_width = 125
newline_style = "Unix"
unstable_features = true

# always use tabs.
hard_tabs = true
tab_spaces = 4

# commas inbetween but not after
match_block_trailing_comma = true
trailing_comma = "Never"

# misc
format_code_in_doc_comments = true
merge_imports = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
