# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "gotham_restful_derive"
version = "0.1.0-rc0"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "RESTful additions for the gotham web framework - Derive"
keywords = ["gotham", "rest", "restful", "web", "http", "derive"]
license = "EPL-2.0 OR Apache-2.0"
repository = "https://gitlab.com/msrd0/gotham-restful"

[lib]
proc-macro = true

[badges]
gitlab = { repository = "msrd0/gotham-restful", branch = "master" }

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0.13"
quote = "1.0.6"
syn = "1.0.22"

[features]
default = []
auth = []
database = []
openapi = []
