# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "gotham_restful_derive"
version = "0.2.0-dev"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "Derive macros for gotham_restful"
keywords = ["gotham", "rest", "restful", "web", "http"]
license = "Apache-2.0"
repository = "https://gitlab.com/msrd0/gotham-restful"
workspace = ".."

[lib]
proc-macro = true

[badges]
gitlab = { repository = "msrd0/gotham-restful", branch = "master" }

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0.13"
quote = "1.0.6"
syn = { version = "1.0.22", features = ["full"] }

[features]
default = []
auth = []
database = []
openapi = []
